services:
  db:
    image: postgres:15-alpine
    container_name: cloud_db
    restart: always
    environment:
      POSTGRES_DB: cloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iamroot
    ports:
      - "5432:5432"


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cloud_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cloud
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: iamroot
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build:
      context: ./netology-diplom-frontend
      dockerfile: Dockerfile
    container_name: cloud_frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    environment:
      - VUE_APP_BASE_URL=http://localhost:8080
