CREATE TABLE IF NOT EXISTS users
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE ,
    login  VARCHAR(50)                         NOT NULL UNIQUE,
    password VARCHAR(500)                         NOT NULL
    );


CREATE TABLE IF NOT EXISTS files
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE ,
    filename VARCHAR(255) NOT NULL,
    size     BIGINT        NOT NULL,
    user_id  BIGINT       NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS blacklist(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE ,
    token       VARCHAR(500) NOT NULL
);

INSERT INTO users (login, password)
VALUES ('mail@mail.com',
        '$2a$12$aSUmvpFwq/LtFVC3/WRRWef1mmF6uxSnuXqWJqHnE8MXoR9GMWyhy');
